### ISSUE TITLE
Support for NFS iTunes Library Files

### ISSUE THREAD

**Issue by mofirouz** [kodiful/plugin.audio.itunesconverter#1]
I have my iTunes Library File on a NFS drive. This seems to be incompatible with this piece of code:

``` python
if not os.path.isfile(library):
```

And this will always return `false` for all NFS files.

**Comment by kodiful** [comment]
Please let me know the following info:
- operating system where Kodi works
- library_path string of iTunes Music Library.xml on NFS

**Comment by mofirouz** [comment]
Hiya,

Thanks for the quick response.
- I'm running Kodi from Android TV.
  - smb://myserver/Music/iTunes/iTunes Music Library.xml

When I input that, it accepts it fine. However on the reload of the plugin, it will come back to the settings pane with a message that says set a library path again. This continues over and over.

Hope this helps,
Mo

On 2 March 2016 at 13:46:05, kodiful (notifications@github.com) wrote:

Please let me know the following info:

operating system where Kodi works
library_path string of iTunes Music Library.xml on NFS

**Comment by kodiful** [comment]
I added a procedure of copying remote "iTunes Music Library.xml" as kodi's working file.
You have to translate the file paths according to your SMB environment.
I hope this will help you.

**Comment by mofirouz** [comment]
Hiya. Thanks so much for this. I can confirm that this is indeed working just fine :) :+1:
